name: uber_ride_clone
description: Riak Tiak Rider app.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  austerity: ^1.1.0
  custom_navigation_bar: ^0.8.2
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.1.0
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.4.3
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  google_maps_directions:
    path: packages/google_maps_directions
  google_maps_flutter: ^2.5.0
  google_place:
    path: packages/google_place
  http: ^1.1.0
  intl: ^0.18.1
  location: ^5.0.3
  permission_handler: ^11.0.1
  shimmer: ^3.0.0
  theme_tailor_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  theme_tailor: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/maps_icons/markers/
    - assets/images/maps_icons/icons/
    - assets/images/maps_icons/
    - assets/images/ads/
    - assets/images/
